### ISSUE TITLE
PhysicalFilesWatcher: Unhandled Exception: System.IO.IOException

### ISSUE THREAD

**Issue by jmajoor** [dotnet/extensions#1902]
### Describe the bug
The (polling) physical file watcher is not protected against possible IO exceptions.
In my case I get the following:
Unhandled Exception: System.IO.IOException: The process cannot access the file '/my/directory' because it is being used by another process.

Most likely cause is a copy operation that happens on a file that was being watched.

### Full Stack Trace
Unhandled Exception: System.IO.IOException: The process cannot access the file '/my/directory' because it is being used by another process.
   at System.IO.FileStatus.EnsureStatInitialized(ReadOnlySpan`1 path, Boolean continueOnError)
   at System.IO.FileSystemInfo.Init(FileStatus& fileStatus)
   at System.IO.FileSystemInfo.Create(String fullPath, String fileName, FileStatus& fileStatus)
   at System.IO.Enumeration.FileSystemEntry.ToFileSystemInfo()
   at System.IO.Enumeration.FileSystemEnumerableFactory.<>c.<FileSystemInfos>b__8_0(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator.TransformEntry(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at Microsoft.Extensions.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.EnumerateFileSystemInfos()+MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Extensions.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Extensions.FileProviders.Physical.PollingWildCardChangeToken.CalculateChanges()
   at Microsoft.Extensions.FileProviders.Physical.PollingWildCardChangeToken.get_HasChanged()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

### Expected behavior
I don't expect an unhandled exception to occur. I either need to be notified on the registered change callback that this exception occurred or have another way of handling this exception. Alternatively the exception could be ignored as the next polling event will detect the change (when the file is no longer locked by another process).

### Additional context
Since this is an unhandled exception in a timer queue thread, my entire aspnet core application crashes and there is no way for me to catch or handle this exception.

**Comment by anurse** [comment]
Can you confirm what versions and OS you are using? The output of `dotnet --info` should give all the information we need.

@mikaelm12 can you take a look? I presume this is Linux from the path, and occurs if a directory being watched by `PhysicalFilesWatcher` is locked. Should be able to try reproducing this in a simple console app.

Might be worth us just catching and logging any `IOException`s that occur in the background timer here. Thoughts @davidfowl ?

**Comment by jmajoor** [comment]
The problem happens inside a docker container (Alpine 3.8).
dotnet --info
Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

The files that are watched are stored on a volume mounted from the docker host (hence I use the polling change monitor). My web service runs fine and picks up changes to the watched files, but sometimes I get this IO exception. In this particular case the docker host was a Windows 10 machine.

**Comment by anurse** [comment]
> The files that are watched are stored on a volume mounted from the docker host (hence I use the polling change monitor)

Ah, that is interesting to know. Especially if you're crossing OS boundaries. We'll see what we can find, but this might be tricky to nail down.

**Comment by jmajoor** [comment]
It may be tricky to reproduce my exact circumstances, but the watcher is simply not protected against any IO Exception. So any IO exception will bring my web app down (as an unhandled exception in the background time thread) whether that is crossing OS boundaries or not.

**Comment by anurse** [comment]
Yeah, that's what I referred to [above](https://github.com/aspnet/Extensions/issues/1902#issuecomment-506823045). It may be that we just add some defensiveness here.
