### ISSUE TITLE
DI scope validation throws for not registered, but unneeded dependency

### ISSUE THREAD

**Issue by epignosisx** [dotnet/extensions#2617]
Ran into this problem while upgrading an app to ASP.NET Core 3.0. Say I have the following:

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace ValidateScopesRepro
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddSingleton<IBar, SomeBar>();
            services.AddSingleton<IBar, SomeOtherBar>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

        }
    }

    public interface IFoo { }
    public interface IBar { }

    public class SomeBar : IBar
    {
        public SomeBar(IFoo foo) { }
    }

    public class SomeOtherBar : IBar { }
}

```

When the app starts scope validation fails because App1 did not register an implementation for `IFoo`. However, this is not necessary, because `SomeBar` is overriden by `SomeOtherBar` which does not need `IFoo`.

Exception thrown:

```cs
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: ValidateScopesRepro.IBar Lifetime: Singleton ImplementationType: ValidateScopesRepro.SomeBar': Unable to resolve service for type 'ValidateScopesRepro.IFoo' while attempting to activate 'ValidateScopesRepro.SomeBar'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ValidateScopesRepro.Program.Main(String[] args) in c:\projects\ValidateScopesRepro\Program.cs:line 16

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: ValidateScopesRepro.IBar Lifetime: Singleton ImplementationType: ValidateScopesRepro.SomeBar': Unable to resolve service for type 'ValidateScopesRepro.IFoo' while attempting to activate 'ValidateScopesRepro.SomeBar'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'ValidateScopesRepro.IFoo' while attempting to activate 'ValidateScopesRepro.SomeBar'.
```

Workaround: disable scope validation

```cs
        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .UseDefaultServiceProvider(opts => opts.ValidateScopes = false)
```

**Comment by alefranz** [comment]
I believe the behaviour is correct here.
With AddSingleton your are not overriding the registration but adding a second one, so for example of you resolve IEnumerable<IBar> you will get both.

**Comment by epignosisx** [comment]
@alefranz that makes sense. However, sounds like in my case where I do not use `IEnumerable<IBar>`, I'm not going to be able to leverage the scope validation feature. Ideally, the current behavior should apply if it finds an `IEnumerable<IBar>` usage.

**Comment by anurse** [comment]
> Ideally, the current behavior should apply if it finds an `IEnumerable<IBar>` usage.

That's not really feasible since you can resolve imperatively using `IServiceProvider.GetService`, so there's no way for us to know that you're never going to use `IEnumerable<IBar>` somewhere.

@alefranz is correct, this is by design. Calling `AddSingleton<IFoo>()` twice **does not override** it actually just adds a second instance. It's only that DI resolve the *last registered instance* when a single `IFoo` is requested that makes it look like you're overriding.
