### ISSUE TITLE
Dependency injection does not work in multiple async threads include backgroundservice

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/extensions#3090]
Hi.I have a service which I inject to my backgroundservice using Dependency Injection.In backgroundservice I have timer which works every 10 seconds and an additional method to send async request using the service I've injected.When I turn off my timer everything works fine,but I need stopless method that send async request every 10 seconds.I think this cause an deadlock or the service I've injected does not properly works inside while loop.Can anyone help me? Thanks

**Comment by davidfowl** [comment]
Can you show some sample code?

**Comment by shahinjabbar** [comment]
I cannot,sorry.Project is confidential

**Comment by shahinjabbar** [comment]
I have got this problem whenever I use httpClient.GetStreamAsync() at this time backgroundservice send async request via injected service every 10 seconds

**Comment by davidfowl** [comment]
You don't need to send me the project, sample code that simulates the problem you are having can wok as well. I don't understand the problem you are having.

It seems like you are trying to stop the method that was kicked off by the timer (the http request) after the timer has stopped? Why?

**Comment by shahinjabbar** [comment]
public Task StartAsync(CancellationToken cancellationToken)
        {
            _timer = new Timer(SendHeartBeat, null, 0, 10000);
             Initialize().GetAwaiter();

            return Task.CompletedTask;
        }

this is my backgroundservice StartAsync method

**Comment by shahinjabbar** [comment]
SendHeartBeat sends httppost request in every 10 seconds

**Comment by shahinjabbar** [comment]
private Timer _timer;
        private readonly IHeartBeatSession _session;
        private readonly ISTPGService _stpgService;
        private bool MustLogOn { get; set; }
        private string jsessionid { get; set; }
        public TestBackgroundService(IHeartBeatSession session, ISTPGService stpgService)
        {
            _session = session;
            _stpgService = stpgService;
        }

**Comment by shahinjabbar** [comment]
Inside Initialize().GetAwaiter() I call my injected service to send another request to get stream ( httpClient.GetStreamAsync() )
Code blocks at these state and throws System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()

**Comment by davidfowl** [comment]
That error looks unrelated to the original question. So you can have piece o code that starts a timer and makes an HTTP request every 10 seconds. Initialize().GetAwaiter() (Why are you calling GetAwaiter in the first place), throws an exception.

Again, what are you trying to solve here?

**Comment by shahinjabbar** [comment]
I need to send heartbeat in every 10 seconds that's why I've create backgroundservice.SendHeartBeat call injected _stpgService and send httppost request.
After calling sendHeartBeat I call Initialize method to do all stuff,I call _stpgService again and I call httpclient.getStreamAsync() to get stream and read stream data

**Comment by davidfowl** [comment]
Why do you call initialize again?

**Comment by shahinjabbar** [comment]
Initialize and SendHeartBeat are different methods.Firstly I need to call SendHeartBeat in every 10 secodns and start Initialize

**Comment by shahinjabbar** [comment]
I get this problem only when I use bgservice.otherwise everything works efficiently
