### ISSUE TITLE
The `AddStandardHedgingHandler` should not require the routing

### ISSUE THREAD

**Issue by martintmk** [dotnet/extensions#4411]
In simple scenarios the caller can provide the URL inline and hedged attempts will go against the same URL. The standard hedging should not force the caller to configure the routes. 

The following should work:

``` csharp
var serviceProvider = new ServiceCollection()
    .AddRedaction()
    .AddHttpClient("my-client")
    .AddStandardHedgingHandler()
    .Services.BuildServiceProvider();

var client = serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient("my-client");

await client.GetAsync("https://www.google.com");
```

Instead, it throws:
```
Unhandled exception. System.InvalidOperationException: The redacted strategy key is an empty string and cannot be used for the strategy selection. Is redaction correctly configured?
   at Microsoft.Shared.Diagnostics.Throw.InvalidOperationException(String message)
   at Microsoft.Extensions.Http.Resilience.Internal.ByAuthorityStrategyKeyProvider.GetStrategyKey(HttpRequestMessage requestMessage)
   at Microsoft.Extensions.Http.Resilience.HttpClientBuilderExtensions.TouchStrategyKey(Func`2 provider)
   at Microsoft.Extensions.Http.Resilience.HttpClientBuilderExtensions.CreateStrategySelector(IServiceProvider serviceProvider, String strategyName)
   at Microsoft.Extensions.Http.Resilience.HttpClientBuilderExtensions.<>c__DisplayClass6_0.<AddResilienceHandler>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass3_0.<AddHttpMessageHandler>b__1(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass6_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Program.<Main>$(String[] args) in C:\Users\martintomka\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 12
   at Program.<Main>(String[] args)
```

**Comment by martintmk** [comment]
Closing as this was tried on older version that does not have this fix yet.

https://github.com/dotnet/extensions/blob/89d758780a703e96952e47e0e8aa507fe81a2cf8/test/Libraries/Microsoft.Extensions.Http.Resilience.Tests/Hedging/StandardHedgingTests.cs#L251
