### ISSUE TITLE
net462 test projects failing to run because they're strongly named.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/extensions#5502]
net462 projects are not running on my machines because the test assemblies are strongly named:

```
[xUnit.net 00:00:02.04]   Starting:    Microsoft.Extensions.AI.Tests (parallel test collections = on [12 threads], stop on fail = off)
[xUnit.net 00:00:03.20] Microsoft.Extensions.AI.Tests: Catastrophic failure: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.AI.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
File name: 'Microsoft.Extensions.AI.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in /_/src/xunit.execution/Sdk/Reflection/ReflectionAssemblyInfo.cs:line 33   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by eiriktsarpalis** [comment]
Adding exclusions via the `sn.exe` tool doesn't seem to address the issue.

**Comment by RussKie** [comment]
Are you able to run other tests on net462? 

I believe this controls the strong naming:
https://github.com/dotnet/extensions/blob/b4734e2101b0ecbf3a0dfad3ed0f1bf807f4cc1c/Directory.Build.targets#L62-L69


...and I think  `InternalsVisibleToDynamicProxyGenAssembly2` item is missing in your test projects.

**Comment by stephentoub** [comment]
What is DynamicProxyGenAssembly2 and why would we need it in our test projects?

Also, tests are passing both in CI and for me locally. Presumably we run the netfx test legs in CI?

**Comment by eiriktsarpalis** [comment]
> Are you able to run other tests on net462?

Yes, net462 tests from `dotnet/runtime` run fine on the same machine for example. But we don't use strong naming in that repo.

**Comment by martincostello** [comment]
> What is DynamicProxyGenAssembly2 and why would we need it in our test projects?

Typically it's a sign of the use of the Moq library for mocks/stubs.

**Comment by RussKie** [comment]
> > Are you able to run other tests on net462?
> 
> Yes, net462 tests from `dotnet/runtime` run fine on the same machine for example. But we don't use strong naming in that repo.

Can you run other net462 tests in dotnet/extensions?

**Comment by RussKie** [comment]
I don't have any problems running the tests:

```
PS D:\Development\dotnet-extensions> .\restore.cmd -vs ai                                                                                                                                               
Build started 14/10/2024 10:48:44 AM.
Generating solution for project "D:\Development\dotnet-extensions\test\TestUtilities\TestUtilities.csproj"
Generating solution for project "D:\Development\dotnet-extensions\src\Libraries\Microsoft.Extensions.AI\Microsoft.Extensions.AI.csproj"
Generating solution for project "D:\Development\dotnet-extensions\src\Libraries\Microsoft.Extensions.AI.Abstractions\Microsoft.Extensions.AI.Abstractions.csproj"
Generating solution for project "D:\Development\dotnet-extensions\src\Libraries\Microsoft.Extensions.AI.AzureAIInference\Microsoft.Extensions.AI.AzureAIInference.csproj"
Generating solution for project "D:\Development\dotnet-extensions\src\Libraries\Microsoft.Extensions.AI.Ollama\Microsoft.Extensions.AI.Ollama.csproj"
Generating solution for project "D:\Development\dotnet-extensions\src\Libraries\Microsoft.Extensions.AI.OpenAI\Microsoft.Extensions.AI.OpenAI.csproj"
Generating solution for project "D:\Development\dotnet-extensions\test\Libraries\Microsoft.Extensions.AI.Abstractions.Tests\Microsoft.Extensions.AI.Abstractions.Tests.csproj"
Generating solution for project "D:\Development\dotnet-extensions\test\Libraries\Microsoft.Extensions.AI.AzureAIInference.Tests\Microsoft.Extensions.AI.AzureAIInference.Tests.csproj"
Generating solution for project "D:\Development\dotnet-extensions\test\Libraries\Microsoft.Extensions.AI.Integration.Tests\Microsoft.Extensions.AI.Integration.Tests.csproj"
Generating solution for project "D:\Development\dotnet-extensions\test\Libraries\Microsoft.Extensions.AI.Ollama.Tests\Microsoft.Extensions.AI.Ollama.Tests.csproj"
Generating solution for project "D:\Development\dotnet-extensions\test\Libraries\Microsoft.Extensions.AI.OpenAI.Tests\Microsoft.Extensions.AI.OpenAI.Tests.csproj"
Generating solution for project "D:\Development\dotnet-extensions\test\Libraries\Microsoft.Extensions.AI.Tests\Microsoft.Extensions.AI.Tests.csproj"
Loading project references...
Loaded 55 project(s) in 644ms
Generating Visual Studio solution "D:\Development\dotnet-extensions\SDK.sln" ...
Updating existing solution file and reusing Visual Studio cache

Success
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.72


PS D:\Development\dotnet-extensions> .\build.cmd         
[INFO] Building D:\Development\dotnet-extensions\SDK.sln...
  C:\Users\igveliko\.nuget\packages\microsoft.dotnet.arcade.sdk\9.0.0-beta.24509.3\tools\Tools.proj      Restore (0.9s)
  Runtime toolset 'dotnet/x64 v8.0.0' already installed.                                                         (1.3s)
  Runtime toolset 'dotnet/x64 v9.0.0-rc.1.24431.7' already installed.                                            (1.7s)
  Runtime toolset 'aspnetcore/x64 v8.0.0' already installed.                                                     (2.1s)
Restore complete (2.1s)
  ...
  Microsoft.Extensions.AI.Abstractions net462 succeeded (1.8s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions\Debug\net462\Microsoft.Extensions.AI.Abstractions.dll
  Microsoft.Extensions.AI.Ollama net462 succeeded (2.1s) → artifacts\bin\Microsoft.Extensions.AI.Ollama\Debug\net462\Microsoft.Extensions.AI.Ollama.dll
  Microsoft.Extensions.AI net462 succeeded (3.3s) → artifacts\bin\Microsoft.Extensions.AI\Debug\net462\Microsoft.Extensions.AI.dll
  Microsoft.Extensions.AI.OpenAI net462 succeeded (4.9s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI\Debug\net462\Microsoft.Extensions.AI.OpenAI.dll
  Microsoft.Extensions.AI.AzureAIInference net462 succeeded (4.9s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference\Debug\net462\Microsoft.Extensions.AI.AzureAIInference.dll
  Microsoft.Extensions.AI.Integration.Tests net462 succeeded (4.9s) → artifacts\bin\Microsoft.Extensions.AI.Integration.Tests\Debug\net462\Microsoft.Extensions.AI.Integration.Tests.dll
  Microsoft.Extensions.AI.Tests net462 succeeded (5.7s) → artifacts\bin\Microsoft.Extensions.AI.Tests\Debug\net462\Microsoft.Extensions.AI.Tests.dll
  Microsoft.Extensions.AI.Abstractions.Tests net462 succeeded (4.1s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions.Tests\Debug\net462\Microsoft.Extensions.AI.Abstractions.Tests.dll
  Microsoft.Extensions.AI.AzureAIInference.Tests net462 succeeded (4.3s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference.Tests\Debug\net462\Microsoft.Extensions.AI.AzureAIInference.Tests.dll 
  Microsoft.Extensions.AI.Ollama.Tests net462 succeeded (1.5s) → artifacts\bin\Microsoft.Extensions.AI.Ollama.Tests\Debug\net462\Microsoft.Extensions.AI.Ollama.Tests.dll
  Microsoft.Extensions.AI.OpenAI.Tests net462 succeeded (2.2s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI.Tests\Debug\net462\Microsoft.Extensions.AI.OpenAI.Tests.dll

Build succeeded in 31.6s
PS D:\Development\dotnet-extensions> .\build.cmd -test   
[INFO] Building D:\Development\dotnet-extensions\SDK.sln...

Build succeeded in 25.2s
```

![Image](https://github.com/user-attachments/assets/01cf8724-eab4-463c-bd90-8e64e421b20e)

**Comment by eiriktsarpalis** [comment]
I tried running the tests again this morning and they seem to be running right now. Not sure why, I had rebooted my machine a few times when I was trying to add the strong names exclusions last week without success. In absence of a reliable repro, I'm going to close this issue.

**Comment by eiriktsarpalis** [comment]
I've started seeing similar issues again:
```
warning : [xUnit.net 00:00:02.75] Skipping: Shared.Tests (could not load dependent assembly 'Shared.Tests, Version=9.1.0'): Could not load file or assembly 'Shared.Tests, Version=9.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```
This reproduces on both x64 and arm64 devices for me.

**Comment by RussKie** [comment]
Something messed up either in your repo or on your workstation. I pulled the latest main and I don't have any issues, the CI is also green... Did you try `git clean -xdf`?

```
PS D:\Development\dotnet-extensions> .\build.cmd -restore -build -test
[INFO] Building D:\Development\dotnet-extensions\SDK.sln...
  C:\Users\user\.nuget\packages\microsoft.dotnet.arcade.sdk\9.0.0-beta.24516.2\tools\Tools.proj      Restore (9.6s)
  C:\Users\user\.nuget\packages\microsoft.dotnet.arcade.sdk\9.0.0-beta.24516.2\tools\Tools.proj     Restore (10.3s)
  Runtime toolset 'dotnet/x64 v9.0.0-rc.1.24431.7' already installed.                                           (10.8s)
  Runtime toolset 'aspnetcore/x64 v8.0.0' already installed.                                                    (11.3s)
Restore complete (11.4s)
  Microsoft.Analyzers.Extra succeeded (3.2s) → artifacts\bin\Microsoft.Analyzers.Extra\Debug\netstandard2.0\Microsoft.Analyzers.Extra.dll
  Microsoft.Analyzers.Local succeeded (1.9s) → artifacts\bin\Microsoft.Analyzers.Local\Debug\netstandard2.0\Microsoft.Analyzers.Local.dll
  TestUtilities net9.0 succeeded (1.4s) → artifacts\bin\TestUtilities\Debug\net9.0\Microsoft.TestUtilities.dll
  TestUtilities net8.0 succeeded (2.2s) → artifacts\bin\TestUtilities\Debug\net8.0\Microsoft.TestUtilities.dll
  Microsoft.Extensions.Compliance.Abstractions net8.0 succeeded (2.3s) → artifacts\bin\Microsoft.Extensions.Compliance.Abstractions\Debug\net8.0\Microsoft.Extensions.Compliance.Abstractions.dll
  TestUtilities net462 succeeded (2.3s) → artifacts\bin\TestUtilities\Debug\net462\Microsoft.TestUtilities.dll
  Microsoft.Extensions.Compliance.Abstractions net9.0 succeeded (2.4s) → artifacts\bin\Microsoft.Extensions.Compliance.Abstractions\Debug\net9.0\Microsoft.Extensions.Compliance.Abstractions.dll
  Microsoft.Extensions.Compliance.Abstractions netstandard2.0 succeeded (2.9s) → artifacts\bin\Microsoft.Extensions.Compliance.Abstractions\Debug\netstandard2.0\Microsoft.Extensions.Compliance.Abstractions.dll
  Microsoft.Gen.Metrics succeeded (3.7s) → artifacts\bin\Microsoft.Gen.Metrics\Debug\netstandard2.0\Microsoft.Gen.Metrics.dll
  Microsoft.Extensions.AI.Abstractions net9.0 succeeded (3.9s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions\Debug\net9.0\Microsoft.Extensions.AI.Abstractions.dll
  Microsoft.Extensions.AI.Abstractions net8.0 succeeded (4.2s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions\Debug\net8.0\Microsoft.Extensions.AI.Abstractions.dll
  Microsoft.Extensions.AI.OpenAI net9.0 succeeded (3.6s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI\Debug\net9.0\Microsoft.Extensions.AI.OpenAI.dll
  Microsoft.Extensions.AI net9.0 succeeded (3.5s) → artifacts\bin\Microsoft.Extensions.AI\Debug\net9.0\Microsoft.Extensions.AI.dll
  Microsoft.Extensions.AI.Ollama net9.0 succeeded (3.9s) → artifacts\bin\Microsoft.Extensions.AI.Ollama\Debug\net9.0\Microsoft.Extensions.AI.Ollama.dll
  Microsoft.Extensions.AI.Abstractions netstandard2.0 succeeded (9.1s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions\Debug\netstandard2.0\Microsoft.Extensions.AI.Abstractions.dll
  Microsoft.Extensions.AI.AzureAIInference net9.0 succeeded (5.7s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference\Debug\net9.0\Microsoft.Extensions.AI.AzureAIInference.dll
  Microsoft.Extensions.AI.OpenAI net8.0 succeeded (5.9s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI\Debug\net8.0\Microsoft.Extensions.AI.OpenAI.dll
  Microsoft.Extensions.AI net8.0 succeeded (6.3s) → artifacts\bin\Microsoft.Extensions.AI\Debug\net8.0\Microsoft.Extensions.AI.dll
  Microsoft.Extensions.AI.Abstractions net462 succeeded (7.3s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions\Debug\net462\Microsoft.Extensions.AI.Abstractions.dll
  Microsoft.Extensions.AI.AzureAIInference net8.0 succeeded (5.8s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference\Debug\net8.0\Microsoft.Extensions.AI.AzureAIInference.dll
  Microsoft.Gen.Logging succeeded (12.8s) → artifacts\bin\Microsoft.Gen.Logging\Debug\netstandard2.0\Microsoft.Gen.Logging.dll
  Microsoft.Extensions.AI.Ollama net462 succeeded (6.1s) → artifacts\bin\Microsoft.Extensions.AI.Ollama\Debug\net462\Microsoft.Extensions.AI.Ollama.dll
  Microsoft.Extensions.AI.OpenAI net462 succeeded (5.0s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI\Debug\net462\Microsoft.Extensions.AI.OpenAI.dll
  Microsoft.Extensions.AI net462 succeeded (6.2s) → artifacts\bin\Microsoft.Extensions.AI\Debug\net462\Microsoft.Extensions.AI.dll
  Microsoft.Extensions.AI.Ollama net8.0 succeeded (1.5s) → artifacts\bin\Microsoft.Extensions.AI.Ollama\Debug\net8.0\Microsoft.Extensions.AI.Ollama.dll
  Microsoft.Extensions.AI.Abstractions.Tests net9.0 succeeded (8.5s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions.Tests\Debug\net9.0\Microsoft.Extensions.AI.Abstractions.Tests.dll
  Microsoft.Extensions.AI.AzureAIInference net462 succeeded (4.4s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference\Debug\net462\Microsoft.Extensions.AI.AzureAIInference.dll
  Microsoft.Extensions.AI.Ollama netstandard2.0 succeeded (2.6s) → artifacts\bin\Microsoft.Extensions.AI.Ollama\Debug\netstandard2.0\Microsoft.Extensions.AI.Ollama.dll
  Microsoft.Extensions.AI netstandard2.0 succeeded (3.4s) → artifacts\bin\Microsoft.Extensions.AI\Debug\netstandard2.0\Microsoft.Extensions.AI.dll
  Microsoft.Extensions.AI.OpenAI netstandard2.0 succeeded (3.1s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI\Debug\netstandard2.0\Microsoft.Extensions.AI.OpenAI.dll
  Microsoft.Extensions.AI.AotCompatibility.TestApp net9.0 succeeded (3.1s) → artifacts\bin\Microsoft.Extensions.AI.AotCompatibility.TestApp\Debug\net9.0\Microsoft.Extensions.AI.AotCompatibility.TestApp.dll
  Microsoft.Extensions.AI.Integration.Tests net8.0 succeeded (7.3s) → artifacts\bin\Microsoft.Extensions.AI.Integration.Tests\Debug\net8.0\Microsoft.Extensions.AI.Integration.Tests.dll
  Microsoft.Extensions.AI.Abstractions.Tests net8.0 succeeded (8.0s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions.Tests\Debug\net8.0\Microsoft.Extensions.AI.Abstractions.Tests.dll
  Microsoft.Extensions.AI.AzureAIInference netstandard2.0 succeeded (2.8s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference\Debug\netstandard2.0\Microsoft.Extensions.AI.AzureAIInference.dll
  Microsoft.Extensions.AI.Integration.Tests net462 succeeded (3.3s) → artifacts\bin\Microsoft.Extensions.AI.Integration.Tests\Debug\net462\Microsoft.Extensions.AI.Integration.Tests.dll
  Microsoft.Extensions.AI.Integration.Tests net9.0 succeeded (5.7s) → artifacts\bin\Microsoft.Extensions.AI.Integration.Tests\Debug\net9.0\Microsoft.Extensions.AI.Integration.Tests.dll
  Microsoft.Extensions.Telemetry.Abstractions net462 succeeded (3.6s) → artifacts\bin\Microsoft.Extensions.Telemetry.Abstractions\Debug\net462\Microsoft.Extensions.Telemetry.Abstractions.dll
  Microsoft.Extensions.AI.Abstractions.Tests net462 succeeded (4.5s) → artifacts\bin\Microsoft.Extensions.AI.Abstractions.Tests\Debug\net462\Microsoft.Extensions.AI.Abstractions.Tests.dll
  Microsoft.Extensions.Telemetry.Abstractions net8.0 succeeded (2.1s) → artifacts\bin\Microsoft.Extensions.Telemetry.Abstractions\Debug\net8.0\Microsoft.Extensions.Telemetry.Abstractions.dll
  Microsoft.Extensions.AI.Ollama.Tests net462 succeeded (2.3s) → artifacts\bin\Microsoft.Extensions.AI.Ollama.Tests\Debug\net462\Microsoft.Extensions.AI.Ollama.Tests.dll
  Microsoft.Extensions.Telemetry.Abstractions net9.0 succeeded (1.7s) → artifacts\bin\Microsoft.Extensions.Telemetry.Abstractions\Debug\net9.0\Microsoft.Extensions.Telemetry.Abstractions.dll
  Microsoft.Extensions.AI.OpenAI.Tests net9.0 succeeded (2.5s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI.Tests\Debug\net9.0\Microsoft.Extensions.AI.OpenAI.Tests.dll
  Microsoft.Extensions.AI.OpenAI.Tests net462 succeeded (2.3s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI.Tests\Debug\net462\Microsoft.Extensions.AI.OpenAI.Tests.dll
  Microsoft.Extensions.AI.Ollama.Tests net9.0 succeeded (1.2s) → artifacts\bin\Microsoft.Extensions.AI.Ollama.Tests\Debug\net9.0\Microsoft.Extensions.AI.Ollama.Tests.dll
  Microsoft.Extensions.Diagnostics.Testing net462 succeeded (3.3s) → artifacts\bin\Microsoft.Extensions.Diagnostics.Testing\Debug\net462\Microsoft.Extensions.Diagnostics.Testing.dll
  Microsoft.Extensions.Diagnostics.Testing net8.0 succeeded (2.6s) → artifacts\bin\Microsoft.Extensions.Diagnostics.Testing\Debug\net8.0\Microsoft.Extensions.Diagnostics.Testing.dll
  Microsoft.Extensions.AI.AzureAIInference.Tests net462 succeeded (1.5s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference.Tests\Debug\net462\Microsoft.Extensions.AI.AzureAIInference.Tests.dll
  Microsoft.Extensions.Diagnostics.Testing net9.0 succeeded (1.7s) → artifacts\bin\Microsoft.Extensions.Diagnostics.Testing\Debug\net9.0\Microsoft.Extensions.Diagnostics.Testing.dll
  Microsoft.Extensions.AI.Ollama.Tests net8.0 succeeded (2.2s) → artifacts\bin\Microsoft.Extensions.AI.Ollama.Tests\Debug\net8.0\Microsoft.Extensions.AI.Ollama.Tests.dll
  Microsoft.Extensions.AI.OpenAI.Tests net8.0 succeeded (2.3s) → artifacts\bin\Microsoft.Extensions.AI.OpenAI.Tests\Debug\net8.0\Microsoft.Extensions.AI.OpenAI.Tests.dll
  Microsoft.Extensions.AI.AzureAIInference.Tests net8.0 succeeded (2.3s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference.Tests\Debug\net8.0\Microsoft.Extensions.AI.AzureAIInference.Tests.dll
  Microsoft.Extensions.AI.Tests net462 succeeded (2.1s) → artifacts\bin\Microsoft.Extensions.AI.Tests\Debug\net462\Microsoft.Extensions.AI.Tests.dll
  Microsoft.Extensions.AI.AzureAIInference.Tests net9.0 succeeded (1.2s) → artifacts\bin\Microsoft.Extensions.AI.AzureAIInference.Tests\Debug\net9.0\Microsoft.Extensions.AI.AzureAIInference.Tests.dll
  Microsoft.Extensions.AI.Tests net9.0 succeeded (2.4s) → artifacts\bin\Microsoft.Extensions.AI.Tests\Debug\net9.0\Microsoft.Extensions.AI.Tests.dll
  Microsoft.Extensions.AI.Tests net8.0 succeeded (3.1s) → artifacts\bin\Microsoft.Extensions.AI.Tests\Debug\net8.0\Microsoft.Extensions.AI.Tests.dll

Build succeeded in 115.8s
```

**Comment by eiriktsarpalis** [comment]
> Did you try `git clean -xdf`

Yes, I generally do this on a daily basis to preserve hygiene.

**Comment by eiriktsarpalis** [comment]
> How do you start the tests?

`dotnet test -f net462` or just VS test. What's funny is that the tests are now running again on the same machines so I'm not entirely sure what's going on. Could it be related to package updates perhaps?

**Comment by RussKie** [comment]
> dotnet test

That won't work, unless you have added the `<repo>\.dotnet` to the PATH. Nor you can just double click on the solution file and open it in VS. You need to use the "helper" scripts (i.e., `build.cmd/sh`).

Have you looked at the instructions in https://github.com/dotnet/extensions/blob/main/docs/building.md?

**Comment by eiriktsarpalis** [comment]
> > dotnet test
> 
> That won't work, unless you have added the `<repo>\.dotnet` to the PATH. Nor you can just double click on the solution file and open it in VS. You need to use the "helper" scripts (i.e., `build.cmd/sh`).

I always add `.dotnet` to my PATH as part of my local workflow, so I don't think that's causing it.

**Comment by RussKie** [comment]
Add or prepend?

**Comment by eiriktsarpalis** [comment]
Prepend. Shouldn't matter though, the issue reproduces both from the CLI and running tests from VS using the solution generated from the build script.

**Comment by RussKie** [comment]
Does the issue repro on another workstation?

**Comment by eiriktsarpalis** [comment]
Yes, both my x64 and arm devices reproduce this.

**Comment by evgenyfedorov2** [comment]
I have the same problem

**Comment by eiriktsarpalis** [comment]
I hit the same problem in an unrelated repo. In that case it turned out that this was caused by coverlet which was inserting instrumentation into strongly named assemblies. I wonder if this might be related.

**Comment by RussKie** [comment]
> I hit the same problem in an unrelated repo. In that case it turned out that this was caused by coverlet which was inserting instrumentation into strongly named assemblies. I wonder if this might be related.

So, the issue is caused by external tools, right? Should this be closed now?

**Comment by eiriktsarpalis** [comment]
Not really. Coverlet is a NuGet package that was part of the other projects build infrastructure -- the issue got resolved as soon as we had it replaced. While dotnet/extensions doesn't appear to use coverlet, perhaps there is some other IL weaving tool that is causing this?

**Comment by RussKie** [comment]
This has been opened for a while; however, I am not sure what exactly the ask here. The issue appears to be caused by environmental configurations on a developer workstation.
