### ISSUE TITLE
OpenAIChatClient streaming tool calls may be broken

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/extensions#5567]
### Description

As of today, some app code that was working before is now failing with:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'bytes')
2024-10-24T15:00:53          at System.ArgumentNullException.Throw(String paramName)
2024-10-24T15:00:53          at System.Text.StringBuilder.Append(Object value)
2024-10-24T15:00:53          at Microsoft.Extensions.AI.OpenAIChatClient.CompleteStreamingAsync(IList`1 chatMessages, ChatOptions options, CancellationToken cancellationToken)+MoveNext()
2024-10-24T15:00:53          at Microsoft.Extensions.AI.OpenAIChatClient.CompleteStreamingAsync(IList`1 chatMessages, ChatOptions options, CancellationToken cancellationToken)+MoveNext()
2024-10-24T15:00:53          at Microsoft.Extensions.AI.OpenAIChatClient.CompleteStreamingAsync(IList`1 chatMessages, ChatOptions options, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

this happens if and only if I try to do function calling with `CompleteStreamingAsync`. It seems that the `FunctionArgumentsUpdate` may now be a `BinaryData` instance that internally holds an empty `_data` value. This causes the exception.

![Image](https://github.com/user-attachments/assets/e8630a4f-cf8c-46bd-866f-942cfd396b74)

Perhaps the underlying OpenAI/AzureOpenAI service has started returning data in a different form.

Or perhaps I've caused this in my own code by some hackery. But I've got a talk to do in a few hours so right now I'm just keeping track of this and putting in this workaround into `CompleteStreamingAsync`:

```cs
if (toolCallUpdate.FunctionArgumentsUpdate is not null
    /* workaround */ && toolCallUpdate.FunctionArgumentsUpdate.ToArray().Length > 0)
{
    _ = (existing.Arguments ??= new()).Append(toolCallUpdate.FunctionArgumentsUpdate);
}
```

### Reproduction Steps

This is in eShopSupport.

If this doesn't repro with other streaming function calling, I'll come back to work out more repro details.

### Expected behavior

No exception

### Actual behavior

Exception

**Comment by stephentoub** [comment]
Can you try explicitly referencing a recent version of System.Memory.Data from your app? I suspect this is a case where the Azure libs are referencing older versions, nothing else in the app is causing it to pull in a newer one, and it's thus missing bug fixes from the last several years.

**Comment by stephentoub** [comment]
e.g. this throws when referencing System.MemoryData 6.0.0
```C#
new BinaryData(ReadOnlyMemory<byte>.Empty).ToString();
```
and succeeds when changing it to 7.0.0.
