### ISSUE TITLE
[Helix] Localization ResourceManagerStringLocalizerTest failures fails on OSX

### ISSUE THREAD

**Issue by HaoK** [dotnet/extensions#627]
These tests pass on Ubuntu/Windows but fail on OSX:

@ryanbrandenburg do you own these tests?

https://mc.dot.net/#/user/dotnet-github-anon-kaonashi-bot/pr~2Faspnet~2Fextensions/ci/20181210.14/workItem/Microsoft.Extensions.Localization.Tests~2Fnetcoreapp2.0/wilogs

```
[xUnit.net 00:00:00.89]     Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.EnumeratorCachesCultureWalkForSameAssembly [FAIL]
[xUnit.net 00:00:00.90]     Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.EnumeratorCacheIsScopedByAssembly [FAIL]
Failed   Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.EnumeratorCachesCultureWalkForSameAssembly
Error Message:
 Assert.Equal() Failure
Expected: 2
Actual:   1
Stack Trace:
   at Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.EnumeratorCachesCultureWalkForSameAssembly() in /_/src/Localization/Localization/test/ResourceManagerStringLocalizerTest.cs:line 54
Failed   Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.EnumeratorCacheIsScopedByAssembly
Error Message:
 Assert.Equal() Failure
Expected: 2
Actual:   1
Stack Trace:
   at Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.EnumeratorCacheIsScopedByAssembly() in /_/src/Localization/Localization/test/ResourceManagerStringLocalizerTest.cs:line 89
[xUnit.net 00:00:00.95]     Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.ResourceManagerStringLocalizer_GetAllStrings_MissingResourceThrows(includeParentCultures: True) [FAIL]
[xUnit.net 00:00:00.95]     Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.ResourceManagerStringLocalizer_GetAllStrings_MissingResourceThrows(includeParentCultures: False) [FAIL]
Failed   Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.ResourceManagerStringLocalizer_GetAllStrings_MissingResourceThrows(includeParentCultures: True)
Error Message:
 Assert.Equal() Failure
Expected: 3
Actual:   1
Stack Trace:
   at Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.ResourceManagerStringLocalizer_GetAllStrings_MissingResourceThrows(Boolean includeParentCultures) in /_/src/Localization/Localization/test/ResourceManagerStringLocalizerTest.cs:line 205
Failed   Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.ResourceManagerStringLocalizer_GetAllStrings_MissingResourceThrows(includeParentCultures: False)
Error Message:
 Assert.Equal() Failure
                                 ↓ (pos 25)
Expected: ···anifest 'testington..resources' was not found.
Actual:   ···anifest 'testington.resources' was not found.
                                 ↑ (pos 25)
Stack Trace:
   at Microsoft.Extensions.Localization.ResourceManagerStringLocalizerTest.ResourceManagerStringLocalizer_GetAllStrings_MissingResourceThrows(Boolean includeParentCultures) in /_/src/Localization/Localization/test/ResourceManagerStringLocalizerTest.cs:line 204
Results File: /Users/dotnet-bot/dotnetbuild/work/2cd806b4-14dc-44a2-bd53-4cb8d54a4b3d/Work/6e7887eb-632e-4309-b1a6-768f390e3c6f/Exec/TestResults/_dci-mac-build-084_2018-12-10_15_43_42.trx

Total tests: 21. Passed: 17. Failed: 4. Skipped: 0.
```

**Comment by HaoK** [comment]
No idea these are just machines in the OSX helix queue, so its possible they never passed since this is the first time we are running them on helix, I can try adding the replace culture but I would be surprised if their machines weren't en-US by default

**Comment by hishamco** [comment]
Is this still happening?
